"""modelos iniciales

Revision ID: 54900f899b88
Revises: 
Create Date: 2026-07-19 10:15:04.859708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54900f899b88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('tipo', sa.Enum('ACCION_COMUNAL', 'PROTECCION_ANIMAL', 'EDUCATIVA', 'UNIVERSIDAD', name='tipocomunidadenum'), nullable=False),
    sa.Column('barrio', sa.String(length=120), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=30), nullable=False),
    sa.Column('email_contacto', sa.String(length=160), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.Enum('COMUNIDAD', 'VETERINARIO', 'LIDER', 'UNIDAD_ESPECIAL', 'ADMIN', name='rolusuarioenum'), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('especie', sa.Enum('PERRO', 'GATO', name='especieenum'), nullable=False),
    sa.Column('sexo', sa.Enum('MACHO', 'HEMBRA', name='sexoenum'), nullable=False),
    sa.Column('edad_estimada', sa.Integer(), nullable=True),
    sa.Column('tamano', sa.Enum('PEQUENO', 'MEDIANO', 'GRANDE', name='tamanoenum'), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('foto_principal', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('CANDIDATO', 'EN_PROCESO', 'VBP_ACTIVO', 'ADOPTADO', 'PERDIDO', 'FALLECIDO', name='estadoanimalenum'), nullable=False),
    sa.Column('esterilizado', sa.Boolean(), nullable=False),
    sa.Column('numero_microchip', sa.String(length=60), nullable=True),
    sa.Column('barrio', sa.String(length=120), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('comunidad_id', sa.Integer(), nullable=False),
    sa.Column('causal_salida', sa.Enum('ADOPCION', 'PERDIDA', 'FALLECIMIENTO', name='causalsalidaenum'), nullable=True),
    sa.Column('fecha_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_salida', sa.String(length=1000), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inscrito_por', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['comunidad_id'], ['comunidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collar_qr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    op.create_index(op.f('ix_collar_qr_codigo'), 'collar_qr', ['codigo'], unique=True)
    op.create_table('evento_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_evento', sa.String(length=60), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporte_novedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reportante_nombre', sa.String(length=120), nullable=False),
    sa.Column('comunidad_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('NUEVO', 'EN_ATENCION', 'ATENDIDO', 'CERRADO', name='estadoreporteenum'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['comunidad_id'], ['comunidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('veterinario', sa.String(length=120), nullable=False),
    sa.Column('veredicto', sa.Enum('APROBADO', 'CON_PENDIENTES', name='veredictovalidacionenum'), nullable=False),
    sa.Column('pendientes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_seguimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('estado_salud', sa.Enum('BUENO', 'REGULAR', 'MALO', name='estadosaludenum'), nullable=False),
    sa.Column('estado_comportamiento', sa.String(length=255), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atencion_especial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('acciones_realizadas', sa.String(length=1000), nullable=False),
    sa.Column('resultado', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['reporte_id'], ['reporte_novedad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atencion_especial')
    op.drop_table('visita_seguimiento')
    op.drop_table('validacion')
    op.drop_table('reporte_novedad')
    op.drop_table('evento_historial')
    op.drop_index(op.f('ix_collar_qr_codigo'), table_name='collar_qr')
    op.drop_table('collar_qr')
    op.drop_table('animal')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('comunidad')
    # ### end Alembic commands ###
    # el DROP TABLE no elimina los tipos ENUM asociados; se limpian a mano
    # para que un upgrade posterior no falle con "type already exists"
    for enum_name in (
        'tipocomunidadenum',
        'rolusuarioenum',
        'especieenum',
        'sexoenum',
        'tamanoenum',
        'estadoanimalenum',
        'causalsalidaenum',
        'estadoreporteenum',
        'veredictovalidacionenum',
        'estadosaludenum',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
